### ISSUE TITLE
Cannot install the pip package.

### ISSUE THREAD

**Issue by Duckrinium** [Aculeasis/rhvoice-wrapper-bin#1]
When running `pip install rhvoice-wrapper-bin`, it gives an error:
```
pip install RHVoice-wrapper-bin
Defaulting to user installation because normal site-packages is not writeable
Collecting RHVoice-wrapper-bin
  Using cached rhvoice-wrapper-bin-0.4.0.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rhvoice-wrapper-data~=0.4.0 in /home/duckrinium/.local/lib/python3.10/site-packages (from RHVoice-wrapper-bin) (0.4.1)
Building wheels for collected packages: RHVoice-wrapper-bin
  Building wheel for RHVoice-wrapper-bin (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      ERROR! Execute ['git', 'describe', '--abbrev=0', '--tags']: Command '['git', 'describe', '--abbrev=0', '--tags']' returned non-zero exit status 128.
      WARNING! Get version from a file: 0.4.0
      running bdist_wheel
      running build
      creating build
      creating build/lib
      creating build/lib/rhvoice_wrapper_bin
      creating build/lib/rhvoice_wrapper_bin/lib
      Clone https://github.com/Olga-Yakovleva/RHVoice.git
      Cloning into 'build/RHVoice'...
      Note: switching to 'ac3458d40358218ebb973e58c74d258bc4c4d7f4'.
      
      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.
      
      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:
      
        git switch -c <new-branch-name>
      
      Or undo this operation with:
      
        git switch -
      
      Turn off this advice by setting config variable advice.detachedHead to false
      
      Compiling RHVoice...
      scons: Reading SConscript files ...
      Mkdir("build/linux")
      Georgian language is skipped because of non-free license
      Checking whether the C compiler works... yes
      Checking whether the C++ compiler works... no
      The C++ compiler is not working
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 164, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 111, in run
          self.execute(executor, scons, 'Compiling RHVoice...')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 338, in execute
          util.execute(func, args, msg, dry_run=self.dry_run)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/util.py", line 344, in execute
          func(*args)
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 81, in executor
          raise RuntimeError('Error executing {} in {}. {}'.format(cmd, str(cwd), err))
      RuntimeError: Error executing ['scons', 'audio_libs=none'] in build/RHVoice. code: 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for RHVoice-wrapper-bin
  Running setup.py clean for RHVoice-wrapper-bin
Failed to build RHVoice-wrapper-bin
Installing collected packages: RHVoice-wrapper-bin
  Running setup.py install for RHVoice-wrapper-bin ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for RHVoice-wrapper-bin did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      ERROR! Execute ['git', 'describe', '--abbrev=0', '--tags']: Command '['git', 'describe', '--abbrev=0', '--tags']' returned non-zero exit status 128.
      WARNING! Get version from a file: 0.4.0
      running install
      /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      creating build/lib
      creating build/lib/rhvoice_wrapper_bin
      creating build/lib/rhvoice_wrapper_bin/lib
      warning: RHVoiceBuild: Use existing source data from build/RHVoice
      
      Compiling RHVoice...
      scons: Reading SConscript files ...
      Mkdir("build/linux")
      Georgian language is skipped because of non-free license
      Checking whether the C compiler works... yes
      Checking whether the C++ compiler works... no
      The C++ compiler is not working
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 164, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 695, in run
          self.run_command('build')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 111, in run
          self.execute(executor, scons, 'Compiling RHVoice...')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 338, in execute
          util.execute(func, args, msg, dry_run=self.dry_run)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/util.py", line 344, in execute
          func(*args)
        File "/tmp/pip-install-iaeenmgo/rhvoice-wrapper-bin_617fffc9504041f69e3245b87715522b/setup.py", line 81, in executor
          raise RuntimeError('Error executing {} in {}. {}'.format(cmd, str(cwd), err))
      RuntimeError: Error executing ['scons', 'audio_libs=none'] in build/RHVoice. code: 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> RHVoice-wrapper-bin

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

OS: openSUSE Tumbleweed
Python version: 3.10

**Comment by Aculeasis** [comment]
You have no C++ compiler so RHVoice wasn't built. I suppose you need to install g++ (or something like https://packages.ubuntu.com/ru/bionic/build-essential package).

Also, you can try to install prebuilded package from releases, `pip install https://github.com/Aculeasis/rhvoice-wrapper-bin/releases/download/0.4.0/rhvoice_wrapper_bin-0.4.0-py3-none-linux_x86_64.whl`

**Comment by Duckrinium** [comment]
Yeah, seems that was the case. Thank you!
